/**
 * ナビゲーションラベル翻訳定数
 * 
 * サイドバーナビゲーション、パンくずリスト、メニュー項目の日本語表示です。
 * 統一されたナビゲーション表現により、直感的なシステム操作を実現します。
 * 
 * Requirements: 2.1, 2.2, 2.3
 */

import { BUSINESS_TERMS } from './business-terms';
import { TECHNICAL_TERMS } from './technical-terms';

export const NAVIGATION_LABELS = {
  // メインナビゲーション
  DASHBOARD: 'ダッシュボード',
  HOME: 'ホーム',
  
  // エンティティ管理
  DEVICES: BUSINESS_TERMS.DEVICES,
  DEVICE_MANAGEMENT: `${BUSINESS_TERMS.DEVICE}管理`,
  DEVICE_SETTINGS: `${BUSINESS_TERMS.DEVICE}設定`,
  DEVICE_DETAILS: `${BUSINESS_TERMS.DEVICE}詳細`,
  DEVICE_PRODUCT_SETTINGS: `${BUSINESS_TERMS.DEVICE}${BUSINESS_TERMS.PRODUCT}設定`,
  APP_RELEASES: 'アプリ配信',
  
  USERS: BUSINESS_TERMS.USERS,
  USER_MANAGEMENT: `${BUSINESS_TERMS.USER}管理`,
  
  CUSTOMERS: BUSINESS_TERMS.CUSTOMERS,
  CUSTOMER_MANAGEMENT: `${BUSINESS_TERMS.CUSTOMER}管理`,
  
  PRODUCTS: BUSINESS_TERMS.PRODUCTS,
  PRODUCT_MANAGEMENT: `${BUSINESS_TERMS.PRODUCT}管理`,
  
  CLASSIFICATIONS: BUSINESS_TERMS.CLASSIFICATIONS,
  CLASSIFICATION_MANAGEMENT: `${BUSINESS_TERMS.CLASSIFICATION}管理`,
  
  PLCS: TECHNICAL_TERMS.PLC,
  PLC_MANAGEMENT: `${TECHNICAL_TERMS.PLC}管理`,
  
  // アラーム関連
  ALARMS: BUSINESS_TERMS.ALARMS,
  ALARM_GROUPS: `${BUSINESS_TERMS.ALARM}${BUSINESS_TERMS.GROUPS}`,
  ALARM_GROUP_MANAGEMENT: `${BUSINESS_TERMS.ALARM}${BUSINESS_TERMS.GROUP}管理`,
  ALARM_ADDRESSES: `${BUSINESS_TERMS.ALARM}${BUSINESS_TERMS.ADDRESSES}`,
  ALARM_PARSE_RULES: `${BUSINESS_TERMS.ALARM}パースルール`,
  
  // 設定関連
  SETTINGS: BUSINESS_TERMS.SETTINGS,
  SYSTEM_SETTINGS: `システム${BUSINESS_TERMS.SETTINGS}`,
  CLIENT_SETTINGS: `クライアント${BUSINESS_TERMS.SETTINGS}`,
  
  // ロギング関連
  LOGGING: BUSINESS_TERMS.LOGGING,
  LOGGING_SETTINGS: `${BUSINESS_TERMS.LOGGING}${BUSINESS_TERMS.SETTINGS}`,
  LOGGING_DATA_SETTINGS: `${BUSINESS_TERMS.LOGGING}${BUSINESS_TERMS.DATA}${BUSINESS_TERMS.SETTINGS}`,
  
  // 効率性関連
  EFFICIENCY: BUSINESS_TERMS.EFFICIENCY,
  EFFICIENCY_SETTINGS: `${BUSINESS_TERMS.EFFICIENCY}${BUSINESS_TERMS.SETTINGS}`,
  
  // IO関連
  IO_SETTINGS: `${TECHNICAL_TERMS.IO}${BUSINESS_TERMS.SETTINGS}`,
  
  // 品質管理関連
  QUALITY_CONTROL: `${BUSINESS_TERMS.QUALITY}${BUSINESS_TERMS.CONTROL}`,
  QUALITY_CONTROL_SIGNALS: `${BUSINESS_TERMS.QUALITY}${BUSINESS_TERMS.CONTROL}${BUSINESS_TERMS.SIGNALS}`,
  
  // 時間関連
  TIME_TABLE: BUSINESS_TERMS.TIMETABLE,
  TIME_MANAGEMENT: '時間管理',
  
  // データ関連
  DATA_DOWNLOAD: `${BUSINESS_TERMS.DATA}${BUSINESS_TERMS.DOWNLOAD}`,
  DATA_MANAGEMENT: `${BUSINESS_TERMS.DATA}管理`,
  
  // 詳細設定関連
  DETAILS_SETTINGS: `詳細${BUSINESS_TERMS.SETTINGS}`,
  
  // パンくずリスト用
  CREATE: '作成',
  EDIT: '編集',
  DETAILS: '詳細',
  LIST: '一覧',
  
  // ページタイトル用
  CREATE_NEW: '新規作成',
  EDIT_ITEM: '編集',
  VIEW_DETAILS: '詳細表示',
  MANAGE_ITEMS: '管理',
  
  // その他
  REPORTS: 'レポート',
  ANALYTICS: '分析',
  MONITORING: 'モニタリング',
  MAINTENANCE: 'メンテナンス',
  BACKUP: 'バックアップ',
  SECURITY: 'セキュリティ',
  AUDIT: '監査',
  HELP: 'ヘルプ',
  SUPPORT: 'サポート',
  DOCUMENTATION: 'ドキュメント',
} as const;

export type NavigationLabel = typeof NAVIGATION_LABELS[keyof typeof NAVIGATION_LABELS];