/**
 * 製品関連翻訳定数
 * 
 * 製品管理機能で使用される翻訳定数を定義します。
 * 製品フィールド、メッセージ、アクションなどの一貫した日本語表示を提供します。
 * 
 * Requirements: 1.2
 */

export const PRODUCT_LABELS = {
  // 製品基本情報
  PRODUCT: '製品',
  PRODUCTS: '製品',
  PRODUCT_NAME: '製品名',
  PRODUCT_ID: '製品ID',
  
  // フィールドラベル
  FIELDS: {
    ID: 'ID',
    INTERNAL_PRODUCT_NUMBER: '社内製品番号',
    CUSTOMER_PRODUCT_NUMBER: '顧客製品番号',
    PRODUCT_NAME: '製品名',
    CUSTOMER_ID: '顧客ID',
    CUSTOMER_NAME: '顧客名',
    CUSTOMER: '顧客',
    DESCRIPTION: '説明',
    CATEGORY: 'カテゴリ',
    SUBCATEGORY: 'サブカテゴリ',
    BRAND: 'ブランド',
    MODEL: 'モデル',
    VERSION: 'バージョン',
    SKU: 'SKU',
    BARCODE: 'バーコード',
    QR_CODE: 'QRコード',
    WEIGHT: '重量',
    DIMENSIONS: '寸法',
    COLOR: '色',
    MATERIAL: '材質',
    UNIT_PRICE: '単価',
    COST_PRICE: '原価',
    CURRENCY: '通貨',
    TAX_RATE: '税率',
    STOCK_QUANTITY: '在庫数量',
    MIN_STOCK_LEVEL: '最小在庫レベル',
    MAX_STOCK_LEVEL: '最大在庫レベル',
    REORDER_POINT: '再注文点',
    LEAD_TIME: 'リードタイム',
    SHELF_LIFE: '賞味期限',
    WARRANTY_PERIOD: '保証期間',
    CREATED_AT: '作成日時',
    UPDATED_AT: '更新日時',
    STATUS: 'ステータス',
    AVAILABILITY: '利用可能性',
    LAUNCH_DATE: '発売日',
    DISCONTINUE_DATE: '販売終了日',
  },
  
  // プレースホルダー
  PLACEHOLDERS: {
    INTERNAL_PRODUCT_NUMBER: '社内製品番号を入力',
    CUSTOMER_PRODUCT_NUMBER: '顧客製品番号を入力',
    PRODUCT_NAME: '製品名を入力',
    CUSTOMER: '顧客を選択',
    DESCRIPTION: '製品の説明を入力',
    CATEGORY: 'カテゴリを選択',
    SUBCATEGORY: 'サブカテゴリを選択',
    BRAND: 'ブランド名を入力',
    MODEL: 'モデル名を入力',
    VERSION: 'バージョンを入力',
    SKU: 'SKUを入力',
    BARCODE: 'バーコードを入力',
    QR_CODE: 'QRコードを入力',
    WEIGHT: '重量を入力',
    DIMENSIONS: '寸法を入力',
    COLOR: '色を入力',
    MATERIAL: '材質を入力',
    UNIT_PRICE: '単価を入力',
    COST_PRICE: '原価を入力',
    CURRENCY: '通貨を選択',
    TAX_RATE: '税率を入力',
    STOCK_QUANTITY: '在庫数量を入力',
    MIN_STOCK_LEVEL: '最小在庫レベルを入力',
    MAX_STOCK_LEVEL: '最大在庫レベルを入力',
    REORDER_POINT: '再注文点を入力',
    LEAD_TIME: 'リードタイムを入力',
    SHELF_LIFE: '賞味期限を入力',
    WARRANTY_PERIOD: '保証期間を入力',
    SEARCH: '製品名で検索...',
    SEARCH_BY_NAME: '製品名で検索...',
    SEARCH_BY_NUMBER: '製品番号で検索...',
    SEARCH_BY_SKU: 'SKUで検索...',
  },
  
  // ヘルプテキスト
  HELP_TEXT: {
    INTERNAL_PRODUCT_NUMBER: '社内で使用する製品識別番号を入力してください（50文字以内）',
    CUSTOMER_PRODUCT_NUMBER: '顧客が使用する製品識別番号を入力してください（50文字以内）',
    PRODUCT_NAME: '製品を識別しやすい名前を入力してください（100文字以内）',
    CUSTOMER: 'この製品を所有する顧客を選択してください',
    DESCRIPTION: '製品に関する詳細情報を入力してください（オプション）',
    SKU: '在庫管理用の一意識別子を入力してください',
    BARCODE: '製品のバーコード番号を入力してください',
    WEIGHT: '製品の重量をグラム単位で入力してください',
    DIMENSIONS: '製品の寸法を「長さ×幅×高さ」の形式で入力してください',
    UNIT_PRICE: '製品の販売単価を入力してください',
    COST_PRICE: '製品の原価を入力してください',
    STOCK_QUANTITY: '現在の在庫数量を入力してください',
    MIN_STOCK_LEVEL: '在庫切れアラートの最小レベルを設定してください',
    REORDER_POINT: '再注文が必要になる在庫レベルを設定してください',
    LEAD_TIME: '注文から納品までの日数を入力してください',
    WARRANTY_PERIOD: '製品保証期間を月単位で入力してください',
    REQUIRED_FIELD: 'このフィールドは必須です',
    OPTIONAL_FIELD: 'このフィールドは任意です',
    UNIQUE_FIELD: 'この値は一意である必要があります',
  },
  
  // 製品ステータス
  STATUS: {
    ACTIVE: 'アクティブ',
    INACTIVE: '非アクティブ',
    DRAFT: '下書き',
    PENDING: '承認待ち',
    APPROVED: '承認済み',
    REJECTED: '却下',
    DISCONTINUED: '販売終了',
    OUT_OF_STOCK: '在庫切れ',
    LOW_STOCK: '在庫少',
    IN_STOCK: '在庫あり',
    BACKORDERED: 'バックオーダー',
    PREORDER: '予約注文',
    COMING_SOON: '近日発売',
    SEASONAL: '季節限定',
    LIMITED_EDITION: '限定版',
    ARCHIVED: 'アーカイブ済み',
  },
  
  // 製品カテゴリ（例）
  CATEGORIES: {
    ELECTRONICS: '電子機器',
    CLOTHING: '衣類',
    FOOD: '食品',
    BOOKS: '書籍',
    TOYS: 'おもちゃ',
    SPORTS: 'スポーツ用品',
    HOME: '家庭用品',
    AUTOMOTIVE: '自動車用品',
    HEALTH: '健康・美容',
    INDUSTRIAL: '産業用品',
    SOFTWARE: 'ソフトウェア',
    SERVICES: 'サービス',
    OTHER: 'その他',
  },
  
  // 通貨
  CURRENCIES: {
    JPY: '日本円',
    USD: '米ドル',
    EUR: 'ユーロ',
    GBP: '英ポンド',
    CNY: '中国元',
    KRW: '韓国ウォン',
    AUD: '豪ドル',
    CAD: 'カナダドル',
    CHF: 'スイスフラン',
    SGD: 'シンガポールドル',
  },
  
  // アクション関連
  ACTIONS: {
    CREATE_PRODUCT: '製品作成',
    EDIT_PRODUCT: '製品編集',
    DELETE_PRODUCT: '製品削除',
    VIEW_PRODUCT: '製品詳細',
    DUPLICATE_PRODUCT: '製品複製',
    ARCHIVE_PRODUCT: '製品アーカイブ',
    RESTORE_PRODUCT: '製品復元',
    EXPORT_PRODUCTS: '製品エクスポート',
    IMPORT_PRODUCTS: '製品インポート',
    BULK_EDIT: '一括編集',
    BULK_DELETE: '一括削除',
    UPDATE_STOCK: '在庫更新',
    UPDATE_PRICE: '価格更新',
    GENERATE_BARCODE: 'バーコード生成',
    GENERATE_QR_CODE: 'QRコード生成',
    PRINT_LABEL: 'ラベル印刷',
    VIEW_HISTORY: '履歴表示',
    GENERATE_REPORT: 'レポート生成',
    SET_FEATURED: '注目製品に設定',
    UNSET_FEATURED: '注目製品から除外',
  },
  
  // メッセージ
  MESSAGES: {
    CREATE_SUCCESS: '製品を作成しました',
    UPDATE_SUCCESS: '製品を更新しました',
    DELETE_SUCCESS: '製品を削除しました',
    DELETE_CONFIRM: 'この製品を削除してもよろしいですか？',
    DELETE_WARNING: '製品を削除すると、関連する注文やデータも影響を受ける可能性があります',
    DUPLICATE_SUCCESS: '製品を複製しました',
    ARCHIVE_SUCCESS: '製品をアーカイブしました',
    RESTORE_SUCCESS: '製品を復元しました',
    EXPORT_SUCCESS: '製品データをエクスポートしました',
    IMPORT_SUCCESS: '製品データをインポートしました',
    BULK_UPDATE_SUCCESS: '製品を一括更新しました',
    STOCK_UPDATED: '在庫を更新しました',
    PRICE_UPDATED: '価格を更新しました',
    BARCODE_GENERATED: 'バーコードを生成しました',
    QR_CODE_GENERATED: 'QRコードを生成しました',
    LABEL_PRINTED: 'ラベルを印刷しました',
    NO_PRODUCTS_FOUND: '製品が見つかりません',
    LOADING_PRODUCTS: '製品情報を読み込み中...',
    LOW_STOCK_WARNING: '在庫が少なくなっています',
    OUT_OF_STOCK_WARNING: '在庫切れです',
    REORDER_REQUIRED: '再注文が必要です',
    FEATURED_SET: '注目製品に設定しました',
    FEATURED_UNSET: '注目製品から除外しました',
  },
  
  // テーブル関連
  TABLE: {
    HEADERS: {
      ID: 'ID',
      INTERNAL_PRODUCT_NUMBER: '社内製品番号',
      CUSTOMER_PRODUCT_NUMBER: '顧客製品番号',
      PRODUCT_NAME: '製品名',
      CUSTOMER_NAME: '顧客名',
      CATEGORY: 'カテゴリ',
      BRAND: 'ブランド',
      SKU: 'SKU',
      UNIT_PRICE: '単価',
      STOCK_QUANTITY: '在庫数量',
      STATUS: 'ステータス',
      CREATED_AT: '作成日',
      UPDATED_AT: '更新日',
      ACTIONS: 'アクション',
      AVAILABILITY: '利用可能性',
      LAST_ORDERED: '最終注文',
    },
    SORT_BY: {
      ID: 'IDでソート',
      INTERNAL_PRODUCT_NUMBER: '社内製品番号でソート',
      CUSTOMER_PRODUCT_NUMBER: '顧客製品番号でソート',
      PRODUCT_NAME: '製品名でソート',
      CUSTOMER_NAME: '顧客名でソート',
      CATEGORY: 'カテゴリでソート',
      BRAND: 'ブランドでソート',
      SKU: 'SKUでソート',
      UNIT_PRICE: '単価でソート',
      STOCK_QUANTITY: '在庫数量でソート',
      STATUS: 'ステータスでソート',
      CREATED_AT: '作成日でソート',
      UPDATED_AT: '更新日でソート',
      AVAILABILITY: '利用可能性でソート',
      LAST_ORDERED: '最終注文でソート',
    },
    EMPTY_STATE: {
      TITLE: '製品がありません',
      DESCRIPTION: '製品を作成して開始してください',
      ACTION: '製品作成',
    },
  },
  
  // ページタイトル
  PAGES: {
    LIST: '製品管理',
    CREATE: '製品作成',
    EDIT: '製品編集',
    DETAIL: '製品詳細',
    INVENTORY: '在庫管理',
    PRICING: '価格管理',
    CATEGORIES: 'カテゴリ管理',
    REPORTS: '製品レポート',
    IMPORT: '製品インポート',
    EXPORT: '製品エクスポート',
  },
  
  // ナビゲーション
  NAVIGATION: {
    PRODUCTS: '製品',
    PRODUCT_LIST: '製品一覧',
    PRODUCT_MANAGEMENT: '製品管理',
    PRODUCT_CATEGORIES: '製品カテゴリ',
    INVENTORY_MANAGEMENT: '在庫管理',
    PRODUCT_REPORTS: '製品レポート',
  },
  
  // フィルター関連
  FILTERS: {
    ALL_STATUS: 'すべてのステータス',
    ACTIVE_ONLY: 'アクティブのみ',
    INACTIVE_ONLY: '非アクティブのみ',
    IN_STOCK_ONLY: '在庫ありのみ',
    OUT_OF_STOCK_ONLY: '在庫切れのみ',
    LOW_STOCK_ONLY: '在庫少のみ',
    DISCONTINUED_ONLY: '販売終了のみ',
    BY_CUSTOMER: '顧客別',
    BY_CATEGORY: 'カテゴリ別',
    BY_BRAND: 'ブランド別',
    BY_PRICE_RANGE: '価格帯別',
    FEATURED_ONLY: '注目製品のみ',
    NEW_PRODUCTS: '新製品',
    POPULAR_PRODUCTS: '人気製品',
    SEASONAL_PRODUCTS: '季節商品',
  },
  
  // バリデーションメッセージ（製品固有）
  VALIDATION: {
    INTERNAL_PRODUCT_NUMBER_REQUIRED: '社内製品番号は必須です',
    INTERNAL_PRODUCT_NUMBER_MAX_LENGTH: '社内製品番号は50文字以内で入力してください',
    INTERNAL_PRODUCT_NUMBER_EXISTS: 'この社内製品番号は既に使用されています',
    CUSTOMER_PRODUCT_NUMBER_REQUIRED: '顧客製品番号は必須です',
    CUSTOMER_PRODUCT_NUMBER_MAX_LENGTH: '顧客製品番号は50文字以内で入力してください',
    CUSTOMER_PRODUCT_NUMBER_EXISTS: 'この顧客製品番号は既に使用されています',
    PRODUCT_NAME_REQUIRED: '製品名は必須です',
    PRODUCT_NAME_MAX_LENGTH: '製品名は100文字以内で入力してください',
    PRODUCT_NAME_EXISTS: 'この製品名は既に使用されています',
    CUSTOMER_REQUIRED: '顧客を選択してください',
    CUSTOMER_INVALID: '有効な顧客を選択してください',
    SKU_EXISTS: 'このSKUは既に使用されています',
    BARCODE_INVALID: '正しいバーコード形式で入力してください',
    WEIGHT_POSITIVE: '重量は正の数値で入力してください',
    UNIT_PRICE_POSITIVE: '単価は正の数値で入力してください',
    COST_PRICE_POSITIVE: '原価は正の数値で入力してください',
    STOCK_QUANTITY_NON_NEGATIVE: '在庫数量は0以上の整数で入力してください',
    MIN_STOCK_LEVEL_NON_NEGATIVE: '最小在庫レベルは0以上の整数で入力してください',
    MAX_STOCK_LEVEL_POSITIVE: '最大在庫レベルは正の整数で入力してください',
    REORDER_POINT_NON_NEGATIVE: '再注文点は0以上の整数で入力してください',
    LEAD_TIME_POSITIVE: 'リードタイムは正の整数で入力してください',
    TAX_RATE_RANGE: '税率は0から100の範囲で入力してください',
    WARRANTY_PERIOD_NON_NEGATIVE: '保証期間は0以上の整数で入力してください',
    DESCRIPTION_MAX_LENGTH: '説明は1000文字以内で入力してください',
    DIMENSIONS_FORMAT: '寸法は「長さ×幅×高さ」の形式で入力してください',
  },
  
  // 単位
  UNITS: {
    GRAMS: 'g',
    KILOGRAMS: 'kg',
    POUNDS: 'lbs',
    OUNCES: 'oz',
    CENTIMETERS: 'cm',
    METERS: 'm',
    INCHES: 'in',
    FEET: 'ft',
    PIECES: '個',
    UNITS: '台',
    BOXES: '箱',
    PACKAGES: 'パッケージ',
    LITERS: 'L',
    MILLILITERS: 'ml',
    GALLONS: 'gal',
    DAYS: '日',
    WEEKS: '週',
    MONTHS: '月',
    YEARS: '年',
    PERCENT: '%',
  },
  
  // 統計・サマリー
  STATISTICS: {
    TOTAL_PRODUCTS: '総製品数',
    ACTIVE_PRODUCTS: 'アクティブ製品数',
    INACTIVE_PRODUCTS: '非アクティブ製品数',
    OUT_OF_STOCK_PRODUCTS: '在庫切れ製品数',
    LOW_STOCK_PRODUCTS: '在庫少製品数',
    TOTAL_INVENTORY_VALUE: '総在庫価値',
    AVERAGE_PRODUCT_PRICE: '平均製品価格',
    PRODUCTS_BY_CATEGORY: 'カテゴリ別製品数',
    PRODUCTS_BY_CUSTOMER: '顧客別製品数',
    TOP_SELLING_PRODUCTS: '売上上位製品',
    SLOW_MOVING_PRODUCTS: '動きの遅い製品',
    NEW_PRODUCTS_THIS_MONTH: '今月の新製品',
    DISCONTINUED_PRODUCTS: '販売終了製品',
    FEATURED_PRODUCTS: '注目製品数',
    INVENTORY_TURNOVER: '在庫回転率',
  },
  
  // レポート関連
  REPORTS: {
    PRODUCT_LIST: '製品一覧レポート',
    INVENTORY_REPORT: '在庫レポート',
    PRICE_LIST: '価格表',
    PRODUCT_CATALOG: '製品カタログ',
    STOCK_VALUATION: '在庫評価レポート',
    REORDER_REPORT: '再注文レポート',
    PRODUCT_PERFORMANCE: '製品パフォーマンスレポート',
    CATEGORY_ANALYSIS: 'カテゴリ分析レポート',
    CUSTOMER_PRODUCTS: '顧客製品レポート',
    DISCONTINUED_PRODUCTS: '販売終了製品レポート',
    NEW_PRODUCTS: '新製品レポート',
    FEATURED_PRODUCTS: '注目製品レポート',
    INVENTORY_AGING: '在庫エイジングレポート',
    PRODUCT_PROFITABILITY: '製品収益性レポート',
  },
  
  // エラーメッセージ
  ERRORS: {
    FETCH_FAILED: '製品情報の取得に失敗しました',
    CREATE_FAILED: '製品の作成に失敗しました',
    UPDATE_FAILED: '製品の更新に失敗しました',
    DELETE_FAILED: '製品の削除に失敗しました',
    DUPLICATE_FAILED: '製品の複製に失敗しました',
    ARCHIVE_FAILED: '製品のアーカイブに失敗しました',
    RESTORE_FAILED: '製品の復元に失敗しました',
    EXPORT_FAILED: '製品データのエクスポートに失敗しました',
    IMPORT_FAILED: '製品データのインポートに失敗しました',
    BULK_UPDATE_FAILED: '製品の一括更新に失敗しました',
    STOCK_UPDATE_FAILED: '在庫の更新に失敗しました',
    PRICE_UPDATE_FAILED: '価格の更新に失敗しました',
    BARCODE_GENERATION_FAILED: 'バーコードの生成に失敗しました',
    QR_CODE_GENERATION_FAILED: 'QRコードの生成に失敗しました',
    LABEL_PRINT_FAILED: 'ラベルの印刷に失敗しました',
    NETWORK_ERROR: 'ネットワークエラーが発生しました',
    PERMISSION_DENIED: 'この操作を実行する権限がありません',
    PRODUCT_NOT_FOUND: '製品が見つかりません',
    INVALID_DATA: '無効なデータです',
    DUPLICATE_PRODUCT: '重複する製品です',
    CUSTOMER_NOT_FOUND: '顧客が見つかりません',
    CATEGORY_NOT_FOUND: 'カテゴリが見つかりません',
    INSUFFICIENT_STOCK: '在庫が不足しています',
    PRODUCT_DISCONTINUED: 'この製品は販売終了しています',
  },
} as const;

// 製品ステータスの型定義
export type ProductStatus = keyof typeof PRODUCT_LABELS.STATUS;
export type ProductStatusLabel = typeof PRODUCT_LABELS.STATUS[ProductStatus];

// 製品カテゴリの型定義
export type ProductCategory = keyof typeof PRODUCT_LABELS.CATEGORIES;
export type ProductCategoryLabel = typeof PRODUCT_LABELS.CATEGORIES[ProductCategory];

// 通貨の型定義
export type ProductCurrency = keyof typeof PRODUCT_LABELS.CURRENCIES;
export type ProductCurrencyLabel = typeof PRODUCT_LABELS.CURRENCIES[ProductCurrency];

// 製品フィールドの型定義
export type ProductField = keyof typeof PRODUCT_LABELS.FIELDS;
export type ProductFieldLabel = typeof PRODUCT_LABELS.FIELDS[ProductField];